"use client";

import {
  Activity,
  BrainCircuit,
  CircleDollarSign,
  TrendingUp,
} from "lucide-react";

type MetricCardsProps = {
  recoveredRevenue: number;
  recoveryRate: number;
  openCases: number;
  aiDecisions: number;
  currency?: string;
};

function formatCurrency(
  value: number,
  currency: string,
) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(value);
}

type MetricCardProps = {
  title: string;
  value: string;
  description: string;
  icon: React.ReactNode;
  iconClassName: string;
};

function MetricCard({
  title,
  value,
  description,
  icon,
  iconClassName,
}: MetricCardProps) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm font-medium text-slate-500">
            {title}
          </p>

          <p className="mt-2 text-2xl font-semibold tracking-tight text-slate-900">
            {value}
          </p>
        </div>

        <div
          className={`flex h-10 w-10 items-center justify-center rounded-lg ${iconClassName}`}
        >
          {icon}
        </div>
      </div>

      <p className="mt-4 text-xs text-slate-500">
        {description}
      </p>
    </div>
  );
}

export default function MetricCards({
  recoveredRevenue,
  recoveryRate,
  openCases,
  aiDecisions,
  currency = "INR",
}: MetricCardsProps) {
  return (
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard
        title="Recovered Revenue"
        value={formatCurrency(
          recoveredRevenue,
          currency,
        )}
        description="Revenue successfully recovered"
        icon={
          <CircleDollarSign className="h-5 w-5 text-emerald-600" />
        }
        iconClassName="bg-emerald-50"
      />

      <MetricCard
        title="Recovery Rate"
        value={`${recoveryRate.toFixed(1)}%`}
        description="Successful recovery outcomes"
        icon={
          <TrendingUp className="h-5 w-5 text-blue-600" />
        }
        iconClassName="bg-blue-50"
      />

      <MetricCard
        title="Open Recovery Cases"
        value={openCases.toLocaleString("en-IN")}
        description="Cases currently requiring recovery"
        icon={
          <Activity className="h-5 w-5 text-amber-600" />
        }
        iconClassName="bg-amber-50"
      />

      <MetricCard
        title="AI Decisions"
        value={aiDecisions.toLocaleString("en-IN")}
        description="Strategies generated by the AI engine"
        icon={
          <BrainCircuit className="h-5 w-5 text-violet-600" />
        }
        iconClassName="bg-violet-50"
      />
    </section>
  );
}